### ISSUE TITLE
Invitation to move to official `eslint-community` org

### ISSUE THREAD

**Issue by MichaelDeBoey** [eslint-community/eslint-plugin-eslint-plugin#297]
We would love to have this repo added to the official [`@eslint-community` organization on GitHub](https://github.com/eslint-community).

As you can read in [the '`@eslint-community` GitHub organization' RFC](https://github.com/eslint/rfcs/tree/main/designs/2022-community-eslint-org), the goal of this new org is to have a place where community members can help ensure widely depended upon ESLint related packages stay up to date with newer ESLint releases and doesn't hold the wider community back.

Since this plugin is (together with `eslint-plugin-node`) [a recommended plugin for linting custom plugins](https://eslint.org/docs/latest/developer-guide/working-with-plugins#linting) & since you —@not-an-aardvark— (according to https://github.com/eslint/rfcs/pull/91#discussion_r887526929) already discussed with @aladdin-add to transfer this repo to a better home, you're welcome to transfer this repository to the new org.

**Comment by not-an-aardvark** [comment]
Thanks. It looks like I don't have permission to transfer this repository to @eslint-community because I'm not allowed to create public repositories in that organization. Seems like there are a few possible workarounds:

- Temporarily adding me as a member to @eslint-community so that I could move the repo there. I would transfer the repository and then leave the organization (since I haven't really been involved in maintaining the plugin recently)
- I could transfer the repository to another person who has the ability to create repositories in @eslint-community, and then that person would subsequently transfer the repository to @eslint-community. (@MichaelDeBoey, not sure if that would be you or someone else -- currently @eslint-community has no public members, but I can't tell if you're a private member.)

**Comment by MichaelDeBoey** [comment]
@not-an-aardvark I've created a team with you (& @aladdin-add?) for this repo & invite you

**Comment by not-an-aardvark** [comment]
I've transferred the repository. Thanks for getting `eslint-community` set up!

Let me know if there's anything else I should do. From skimming [this](https://github.com/eslint/rfcs/tree/main/designs/2022-community-eslint-org), it seems like I should add `@eslintbot` as an owner to the NPM package?

**Comment by MichaelDeBoey** [comment]
I think it would be good to add both `@eslintbot`, myself (`@michaeldeboey`) & @nzakas

**Comment by not-an-aardvark** [comment]
Ok, I've added those three accounts.

**Comment by MichaelDeBoey** [comment]
Probably also a good idea to add the `eslint-community` npm org
