### ISSUE TITLE
Rule: require a meta.docs.recommended

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [eslint-community/eslint-plugin-eslint-plugin#446]
Similar to `require-meta-docs-description` and `require-meta-docs-url`: it's common for plugin rules to specify to specify a `meta.docs.description` value. For example, in `eslint-plugin-eslint-plugin`: https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/b8ed4caa9b0ffeb0e12c44824ccee5428345e90b/lib/rules/consistent-output.js#L22

Not every plugin enforces a `meta.docs.recommended` & correspondingly named ruleset, so I'm not sure whether this should be enabled by default in this plugin's `recommended` ruleset. But it'd be nice to at least have the rule available, I think.

Filing this as a continuation of https://github.com/eslint/eslint/pull/18005#discussion_r1458066983.  At least ESLint core does this ad hoc.

**Comment by bmish** [comment]
Is this issue about `meta.docs.description` or `meta.docs.recommended`? Note we have this rule:

* https://github.com/eslint-community/eslint-plugin-eslint-plugin/blob/main/docs/rules/require-meta-docs-description.md

**Comment by JoshuaKGoldberg** [comment]
Sorry, copypasta issue on the title 😅

**Comment by bmish** [comment]
Regarding `meta.docs.recommended`, I'd welcome a rule for this for plugins that want to use it, but I don't think it should be recommended.

This property can be useful, as some plugins have scripts that generate their `recommended` config based on it, and having the flag readily accessible in the rule can be convenient. However, it can also be considered duplicative of the config itself, requiring extra tooling to keep the two in sync. And it doesn't really scale well to plugins that have multiple configs, don't have a recommended config, or simply prefer to keep the source of truth solely in the configs themselves rather than in the rules.
